config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/index'

  # WEB UI
  root to: 'home#index'
  resources :orders
  resources :batches

  get 'users', to: 'registrations#index'

  devise_for :users # , path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # custom for list users
  # API
  namespace :api do
    namespace :v1 do
      # get 'orders', to: 'orders#index'
      get 'orders/status', to: 'orders#status'
      get 'orders/channel', to: 'orders#purchase_channel'
      post 'orders', to: 'orders#create'
      put 'orders', to: 'orders#update'

      post 'batches', to: 'batches#create'
      put 'batches/close', to: 'batches#close_orders'
      put 'batches/sent', to: 'batches#sent_orders'

      get 'reports/financial', to: 'reports#financial_report'

      post 'sign_up', to: 'registrations#create'
      get 'users', to: 'registrations#index'
      # devise_for :users, defaults: { format: :json }, as: :users
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/batch.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: batches
#
#  id               :bigint           not null, primary key
#  purchase_channel :string
#  reference        :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  user_id          :bigint           not null
#
# Indexes
#
#  index_batches_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Batch < ApplicationRecord
  validates_presence_of :purchase_channel

  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :orders
end

app/controllers/api/v1/batches_controller.rb
# frozen_string_literal: true

class Api::V1::BatchesController < Api::V1::ApiController
  # before_action :set_batch, only: %i[show edit update destroy]

  before_action :require_authorization!
  include OrdersHelper

  # PUT
  def close_orders
    @reference = params[:reference]
    @batch = Batch.where(reference: @reference)[0]
    i = 0
    @batch.orders.each do |o|
      next unless o.status == 'PRODUCTION'

      i += 1
      o.status = 'CLOSED'
      o.save
    end
    render json: "Updated #{i} orders to status closed", status: :ok
  end

  def sent_orders
    @batch = Batch.where(reference: params[:reference])[0]
    @orders = Order.where(batch: @batch).where(delivery_service: params[:delivery_service])
    @orders.each do |o|
      o.status = 'SENT'
      o.save
    end
    render json: "Updated #{@orders.size} orders to status SENT", status: :ok
  end

  # POST /batches
  def create
    @batch = Batch.new(batch_params.merge(reference: random_reference('BR')))
    @orders = load_orders_by(current_user, @batch.purchase_channel)

    if current_user.admin
      render json: 'Operation don\'t permited to admin user', status: :unauthorized
    elsif @orders.size <= 0
      render json: 'Operation can\'t be completed. Don\'t have orders pending of producing',
             status: :unprocessable_entity
    elsif @batch.save
      inlcude_orders_in_batch(@orders, @batch)
      render json: "{\"reference\":\"#{@batch.reference}\", \"qtd_orders\":#{@orders.size}}", status: :created
    else
      render json: @batch.errors, status: :unprocessable_entity
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_batch
    @batch = Batch.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def batch_params
    params.require(:batch).permit(:reference, :purchase_channel)
  end

  def require_authorization!
    render json: '{}', status: :forbidden unless current_user.admin
  end
end

app/controllers/batches_controller.rb
# frozen_string_literal: true

# Class with control the batches
class BatchesController < ApplicationController
  before_action :set_batch, only: %i[show edit update destroy]
  require 'securerandom'

  # GET /batches
  # GET /batches.json
  def index
    @batches = if current_user.admin
                 Batch.all
               else
                 Batch.where(user_id: current_user.id)
               end
  end

  # GET /batches/1
  # GET /batches/1.json
  def show; end

  # GET /batches/new
  def new
    @batch = Batch.new
  end

  # POST /batches
  # POST /batches.json
  def create
    @batch = Batch.new(batch_params.merge(reference: random_reference('BR')))
    @orders = load_orders_by(current_user, @batch.purchase_channel)

    respond_to do |format|
      if @orders.size <= 0
        format.html { redirect_to :index, notice: 'Operation can\'t be completed. Don\'t have orders pending of producing' }
      elsif @batch.save
        inlcude_orders_in_batch(@orders, @batch)
        format.html { redirect_to @batch, notice: 'Batch was successfully created.' }
        format.json { render :show, status: :created, location: @batch }
      else
        format.html { render :new }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_batch
    @batch = Batch.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def batch_params
    params.require(:batch).permit(:reference, :purchase_channel)
  end
end

app/helpers/api/v1/batches_helper.rb
module Api::V1::BatchesHelper
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/views/batches/_form.html.slim
= simple_form_for(@batch) do |f|
  .row
    /.col-md-3
      = f.input :reference, disabled: true
    .col-md-3
      = f.input :purchase_channel
  .action
    = f.submit class: 'btn btn-success'
    '
    = link_to t('.cancel', default: t('helpers.links.cancel')),
              batches_path,
              class: 'btn btn-danger'

app/views/batches/edit.html.slim
.col-md-12
  .card
    .card-header
      h3 class="card-title" = t '.title'
    .card-body
      == render 'form'

app/views/batches/index.html.slim
- model_class = Batch

.col-md-12
  .card
    .card-header
      h3 class="card-title" = t '.title'
    .card-body
      div id="toolbar"
        div class="form-inline" role="form"
          .form-group
            = link_to fas_icon('plus') + ' ' + t('.new'),
                      new_batch_path,
                      class: 'btn btn-primary'
      table[
          data-toggle="table"
          data-pagination="true"
          data-search="true"
          data-advanced-search="true"
          data-id-table="advancedTable"
          data-toolbar="#toolbar
          data-page-size="10
          id="table-batches"]
        thead
          tr
            th = model_class.human_attribute_name(:reference)
            th = model_class.human_attribute_name(:purchase_channel)
            th = model_class.human_attribute_name(:order)
            - if current_user.admin
              th = model_class.human_attribute_name(:user)

            th = model_class.human_attribute_name(:created_at)
            th = model_class.human_attribute_name(:updated_at)
            th
            /th
            /th
        tbody
          - @batches.each do |batch|
            tr
              td = batch.reference
              td = batch.purchase_channel
              th = batch.orders.size
              - if current_user.admin
                td = batch.user.email

              td = batch.created_at.strftime('%d/%m/%Y - %H:%M')
              td = batch.updated_at.strftime('%d/%m/%Y - %H:%M')
              td = link_to fas_icon('eye'), batch
              /td = link_to fas_icon('pencil-alt'), edit_batch_path(batch)
              /td = link_to fas_icon('trash-alt'),
                            batch,
                            data: { confirm: 'Are you sure?' },
                            method: :delete

javascript:
  $(function() {
      $('#table-batches').bootstrapTable()
  })

app/views/batches/new.html.slim
.col-md-12
  .card
    .card-header
      h3 class="card-title" = t '.title'
    .card-body
      == render 'form'

app/views/batches/show.html.slim
- model_class = Batch

.col-md-12
  .card
    .card-header
      h3 class="card-title" = t '.title'
    .card-body
      p
        strong = model_class.human_attribute_name(:reference)
        ':
        = @batch.reference
      p
        strong = model_class.human_attribute_name(:purchase_channel)
        ':
        = @batch.purchase_channel

    .card-footer
      => link_to t('.edit'), edit_order_path(@order), class: 'btn btn-warn'
      '|
      =< link_to t('.back'), orders_path, class: 'btn btn-success'