config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/index'

  # WEB UI
  root to: 'home#index'
  resources :orders
  resources :batches

  get 'users', to: 'registrations#index'

  devise_for :users # , path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # custom for list users
  # API
  namespace :api do
    namespace :v1 do
      # get 'orders', to: 'orders#index'
      get 'orders/status', to: 'orders#status'
      get 'orders/channel', to: 'orders#purchase_channel'
      post 'orders', to: 'orders#create'
      put 'orders', to: 'orders#update'

      post 'batches', to: 'batches#create'
      put 'batches/close', to: 'batches#close_orders'
      put 'batches/sent', to: 'batches#sent_orders'

      get 'reports/financial', to: 'reports#financial_report'

      post 'sign_up', to: 'registrations#create'
      get 'users', to: 'registrations#index'
      # devise_for :users, defaults: { format: :json }, as: :users
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/partials/_navbar.html.slim
nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary"
  .container
    a class="navbar-brand" href="#"
      = t('.title')
    button[
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"]
      span class="navbar-toggler-icon"

    div class="collapse navbar-collapse" id="navbarSupportedContent"
      - if user_signed_in?
        / grupo de botões da direita
        ul class="navbar-nav mr-auto"
          li class="nav-item active"
            = link_to root_path, class: 'nav-link'
              = t('.home')
              span class="sr-only"
                '(current)
          - if current_user.admin
            li class="nav-item"
              = link_to batches_path, class: 'nav-link'
                = t '.batches'
          li class="nav-item"
            = link_to orders_path, class: 'nav-link'
              = t '.orders'
          li class="nav-item"
            = link_to users_path, class: 'nav-link'
              = t '.users'

        span class="navbar-text"
          = "Logado como: #{current_user.name} "

        ul class="navbar-nav"
          li class="nav-item"
            = link_to destroy_user_session_path,
                      data: { method: :delete },
                      class: 'nav-link' do
              span
                = fas_icon('sign-out-alt')
                'Sair